# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43f49bbb3099aebc4e88a36c6a594f594b127f35a899ed8aa9627799758da1585ca90115b26c7137aba9913ed189d3d537d7f1b7a896c2abfd729081af1d0b17

test:
  secret_key_base: c774ec5dce6976a2314035121a513584ea2f3c4e873590965d638e238ea08663fe4c823256eedb6ccf3f175fa426b650be0c868cdc312cd08540db2d1b3a6436

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
